exports.getRandomQuestion = function() {
  var randomIndex = Math.floor(Math.random() * questions.length);
  return questions[randomIndex];
};

questions = [
  // Hypothetical scenarios, unrelated to the self
  "If you ruled the world, what would be the first thing you would change?",
  "If you won the lottery, what would you do with the money?",
  "If you could go back in time to change one thing what would it be?",
  "If you could live anywhere, where would it be?",
  "If you could ask your future self one question, what would it be?",
  "If you could un-invent one thing, what would it be?",
  "If you could time travel, what would you do?",
  "If you could eat lunch with one famous person, who would it be?",
  "If you could live in any city in the world, where would it be?",
  "If you could only eat one food for the rest of your life, what would it be?",
  "If you could have any superpower, which one would you pick?",
  "If you could change one thing about the world, what would it be?",
  "If you could steal one thing in the world, what would it be?",
  "If you went to a psychiatrist, what would he/she say you suffer from?",
  "If your house was on fire, what's the one thing you'd want to take with you?",
  "What cartoon character would you love to see in 21st century life?",
  "What thing would you like to bring back into fashion?",
  "What would your dream house look like?",
  "What would be the name of your debut solo album?",
  "Which fictional character do you wish was real?",
  "Who would you want to be with on a desert island?",
  "How would you dispose of a dead body?",
  "How would you describe your dream job?",

  // Self-reflection
  "Are you a good liar?",
  "How is your relationship with your parents?",
  "Is there anything about the opposite sex you just don't understand?",
  "If you could change anything about yourself what would it be?",
  "If you could go back and relive a day in your life, what would you change?",
  "If money was no object, what would you be doing with your life?",
  "If you only had one day left to live, what would you do?",
  "If you had a warning label, what would yours say?",
  "What do you do when you forget someone's name immediately after they've introduced themselves?",
  "What quality about yourself do you value most?",
  "What are you most proud about in your life?",
  "What makes you nervous?",
  "What do you get compulsive about?",
  "What do you think about the most?",
  "What makes you nostalgic?",
  "What are you good at?",
  "What is the weirdest thing about you?",
  "What is something about you that people wouldn't expect?",
  "What is the first thing you notice when you meet someone new?",
  "What is one thing you miss about being a kid?",
  "What is the best decision you've made so far?",
  "What is the best piece of advice anyone has ever given you?",
  "What is one of your worst habits?",
  "What is one thing that you want to do before you get old?",
  "What is your biggest pet peeve?",
  "What are you looking forward to?",
  "What would you like to spend more time doing?",
  "What were you like as a kid?",
  "What did you want to be when you grew up before you started college?",
  "Where do you see yourself in five years?",

  // Subjective history
  "What is your favorite childhood memory?",
  "What is your greatest accomplishment?",
  "What is the worst present you've ever gotten?",
  "What is the most unusual thing you've ever eaten?",
  "What is the most memorable rumor you've heard about yourself?",
  "What is the scariest thing you've ever done?",
  "What is the craziest thing you've ever done?",
  "What is been the happiest moment in your life so far?",
  "What is your favorite memory at college?",
  "What is the nicest thing someone else has done for you?",
  "What is something embarrassing that happened to you?",
  "What is one thing you always wanted as a kid, but never got?",
  "What is your best memory of a vacation?",

  // Objective history
  "Have you ever been admitted to the hospital?",
  "Have you ever had any brushes with the law?",
  "Have you ever accidentally injured anyone?",
  "Have you ever been in a fight?",
  "Have you ever started a rumor?",
  "Have you ever stolen anything?",
  "When did you stop believing in Santa?",
  "What is one thing that you learned this week?",
  "What is the longest period of time you've gone without sleep?",
  "What is the last thing you do before you go to sleep?",
  "What is your first memory?",
  "What was the last social faux pas you made?",
  "What was your first detention for?",
  "What was your last dream about?",
  "What was the last thing you thought about last night?",
  "Who was your first crush?",
  "Who was your first best friend?",

  // Opinions/Preferences
  "Do you believe in soul mates?",
  "Do you believe in love at first sight?",
  "Do you believe in destiny or free will?",
  "What does your vision of a utopian society look like?",
  "What do college students do too much of today?",
  "What is one thing you would change about your school?",
  "What is the greatest invention of all time?",
  "What is your favorite song?",
  "What is your favorite Pokemon character?",
  "What is your favorite Disney movie?",
  "What kind of music do you like to listen to?",
  "What song annoys you the most?"
];
